export const ROUTES = {
  PUBLIC: {
    HOME: '/',
    SHOP: '/shop',
    PRODUCT_DETAIL: '/product/:slug',
    SEARCH: '/search',
    WISHLIST: '/wishlist',
    CART: '/cart',
  },
  AUTH: {
    LOGIN: '/login',
    REGISTER: '/register',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
  },
  CUSTOMER: {
    ACCOUNT: '/account',
    PROFILE: '/account/profile',
    ORDERS: '/account/orders',
    ORDER_DETAILS: '/account/orders/:id',
    WISHLIST: '/account/wishlist',
    ADDRESSES: '/account/addresses',
  },
  CHECKOUT: {
    CART: '/cart',
    CHECKOUT: '/checkout',
    CONFIRMATION: '/checkout/confirmation/:orderNumber',
  },
  ADMIN: {
    DASHBOARD: '/admin',
    LOGIN: '/admin/login',
    PRODUCTS: '/admin/products',
    CATEGORIES: '/admin/categories',
    ORDERS: '/admin/orders',
    REVIEWS: '/admin/reviews',
    CONTACTS: '/admin/contacts',
    MEDIA: '/admin/media',
    ANALYTICS: '/admin/analytics',
    SETTINGS: '/admin/settings',
    LOGS: '/admin/logs',
  },
} as const;
